// <auto-generated />
using Forma.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Forma.Infrastructure.Migrations
{
    [DbContext(typeof(FormaDbContext))]
    [Migration("20260311000001_RemoveUsernameUniqueConstraint")]
    partial class RemoveUsernameUniqueConstraint
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
