// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using WebAPI1.Context;

#nullable disable

namespace WebAPI1.Migrations
{
    // 手動補的 migration（沒有經過 `dotnet ef migrations add` 產生，因為這個專案的
    // Program.cs 用的是 top-level statements + 直接呼叫 db.Database.Migrate()/種子資料，
    // design-time 工具會把整段連到 appsettings.json 裡設定的正式資料庫，風險太高不敢跑）。
    // BuildTargetModel 這裡故意留空、不是完整的模型快照——不影響 Migrate() 在啟動時套用
    // 這個 migration（那只看 [Migration] 屬性 + Up()），只是代表之後如果要再用
    // `dotnet ef migrations add` 加新的 migration，第一次執行前要先重新產生一份完整、
    // 正確的 Designer.cs（在安全、可以連測試用資料庫的環境下跑，不要對著正式站連線字串跑）。
    [DbContext(typeof(ISHAuditDbcontext))]
    [Migration("20260918120000_AddMcpOAuthServer")]
    partial class AddMcpOAuthServer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);
#pragma warning restore 612, 618
        }
    }
}
